name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

env:
  cache-version: v0.2

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Restore data cache
        uses: actions/cache/restore@v4
        id: restore-data-cache
        with:
          path: src/generated/
          key: ${{ env.cache-version }}-data-${{ hashFiles('src/generated/*.json') }}
          restore-keys: |
            ${{ env.cache-version }}-data-

      # - name: Fetch data from microCMS
      #   run:

      - name: Restore cached images
        id: cache-images-restore
        uses: actions/cache/restore@v4
        with:
          path: node_modules/.astro/
          key: ${{ env.cache-version }}-images-${{ hashFiles('src/generated/*.json') }}
          restore-keys: ${{ env.cache-version }}-images-

      - name: Install, build, and upload your site
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
        uses: withastro/action@v3
        with:
          node-version: 22

      - name: Save cached data
        id: cache-data-save
        uses: actions/cache/save@v4
        with:
          path: src/generated/
          key: ${{ env.cache-version }}-data-${{ hashFiles('src/generated/*.json') }}

      - name: Save cached images
        id: cache-images-save
        uses: actions/cache/save@v4
        with:
          path: node_modules/.astro/
          key: ${{ env.cache-version }}-images-${{ hashFiles('src/generated/*.json') }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
